# Site settings
title: 2015年度後期 計算機科学第一
description: > # this means to ignore newlines until "baseurl:"
  青谷先生が担当された計算機科学概論演習に続いて，Scalaを用いたプログラミングについて学びましょう．
url: "http://wakita.github.io"
baseurl: "/cs1" # the subpath of your site, e.g. /blog/

author: 脇田建
email: wakita@is.titech.ac.jp
github_username:  wakita

owner:
  name: 脇田建
  email: wakita@is.titech.ac.jp
  github_username:  wakita

encoding: utf-8

moruku:
  use_tex: false
  use_divs: false
  png_engine: blahtex
  png_dir: img/tex
  png_url: /img/tex
  fenced_code_blocks: true

# Build settings
github: [Repository metadata]
timezone: Japan/Tokyo

markdown: kramdown
# markdown: KramdownPygments
highlighter: pygments
# https://github.com/mvdbos/kramdown-with-pygments

#paginate: 5
#pagenate_path: "posts/:num"
